#define NORMAL_ACCELERATION 50
#define FAST_ACCELERATION 100

#define NORMAL_SPEED 250
#define FAST_SPEED 450
#define REVERSE_SPEED -200

#define WIFI_SSID "Hanma"
#define WIFI_PASSWORD "2Y-LYBQzeipA"